### ISSUE TITLE
Error with 1.7.X servers

### ISSUE THREAD

**Issue by Charadon** [haveric/StackableItems#128]
When the server starts up, this error occurs.
[05:34:18] [Server thread/INFO]: [StackableItems] Enabling StackableItems v1.0.5
[05:34:19] [Server thread/ERROR]: Error occurred while enabling StackableItems v1.0.5 (Is it up to date?)
java.lang.NullPointerException
	at haveric.stackableItems.util.SIItems.loadItemsFile(SIItems.java:199) ~[?:?]
	at haveric.stackableItems.util.SIItems.reload(SIItems.java:113) ~[?:?]
	at haveric.stackableItems.util.SIItems.init(SIItems.java:76) ~[?:?]
	at haveric.stackableItems.StackableItems.onEnable(StackableItems.java:48) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]

Now, the plugin works fine. But it spams an error in the console everytime someone clicks an item:
[05:25:05] [Server thread/ERROR]: Could not pass event InventoryDragEvent to StackableItems v1.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.Container.clickItem(Container.java:184) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1443) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:15) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.handle(PacketPlayInWindowClick.java:65) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.validate(CraftScheduler.java:397) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:119) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:102) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:85) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	at haveric.stackableItems.util.InventoryUtil.replaceItem(InventoryUtil.java:1070) ~[?:?]
	at haveric.stackableItems.listeners.SIPlayerListener.inventoryDrag(SIPlayerListener.java:598) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1646.jar:git-Spigot-1646]
	... 14 more

Dunno what can be done about it. But I might as well put it here. I did run debug_mode but it gave the same errors, so it didn't add anything.
I'm using spigot-1.7.9-R0.3-SNAPSHOTBuild1543

**Comment by Charadon** [comment]
I fixed it, use java 8
