### ISSUE TITLE
Task #[NUMBER] for StackableItems v1.2.0 generated an exception: java.lang.AssertionError: TRAP

### ISSUE THREAD

**Issue by Greymagic27** [haveric/StackableItems#176]
This is an error that appears at random points in my server and I haven't found the exact cause yet. I've attached a link to the full error: https://paste.gg/p/anonymous/60e7f72bf72342088994941527bd3010

**Comment by haveric** [comment]
Are you able to narrow down what specifically you were doing before this error occurred?

**Comment by Greymagic27** [comment]
It's only been noticed in the console after the fact and only when other users were online, not when I was online unfortunately

**Comment by Greymagic27** [comment]
If it is when you craft into a custom set stack then I can't reproduce it.

**Comment by CommandoEchino** [comment]
I have also experienced this issue. It started happening almost immediately after adding this plugin to my server. The culprit turned out to be one of my players stacking 64 totems in their inventory:

![image](https://user-images.githubusercontent.com/64720141/231336772-9342135f-7e10-4dea-a35f-bf8c199afa58.png)

**Comment by CloudeLecaw** [comment]
we also have this issue on our server and dont use any Traps to stack.. we also dont know at the moment what causes this...
```

[06:56:32] [Server thread/WARN]: [StackableItems] Task #3682138 for StackableItems v1.2.0 generated an exception
java.lang.AssertionError: TRAP
	at net.minecraft.world.item.ItemStack.updateEmptyCacheFlag(ItemStack.java:254) ~[paper-1.19.4.jar:git-Paper-521]
	at net.minecraft.world.item.ItemStack.setCount(ItemStack.java:1321) ~[paper-1.19.4.jar:git-Paper-521]
	at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.setAmount(CraftItemStack.java:148) ~[paper-1.19.4.jar:git-Paper-521]
	at haveric.stackableItems.util.InventoryUtil.lambda$addItems$0(InventoryUtil.java:474) ~[StackableItems_1.2.0_SelfCompiled.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-521]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-521]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-521]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-521]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-521]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-521]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-521]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by AyalX** [comment]
We are also receiving this exception in console repeatedly:

```
[18:27:24 WARN]: [StackableItems] Task #923757 for StackableItems v1.2.0 generated an exception
java.lang.AssertionError: TRAP
        at net.minecraft.world.item.ItemStack.updateEmptyCacheFlag(ItemStack.java:255) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.world.item.ItemStack.setCount(ItemStack.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.setAmount(CraftItemStack.java:148) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at haveric.stackableItems.util.InventoryUtil.lambda$addItems$0(InventoryUtil.java:447) ~[StackableItems.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by haveric** [comment]
I have yet to be able to replicate this issue. If anyone who is experiencing it could help by zipping up their server and sending it to me for testing, that would be extremely helpful. Please feel free to reach out on discord as well.
